### ISSUE TITLE
Cannot apply texture on 000.obj 

### ISSUE THREAD

**Issue by MilesTheProwler** [qzane/textured_smplx#7]
Can someone help me about why I cannot apply the texture from textured_smplx\data\obj1\smpl\meshes\P01125-150055\000.obj ? Only smpl_uv.obj can apply the output texture image. 

Thanks.

**Comment by qzane** [comment]
That's because the "000.obj" file (produced by smplify or VIBE) doesn't come with texture information, to visualize that, I suggest you make a copy of "smpl_uv.obj" and replace every lines that start with 'v ' (there is a space after v because you don't want to change the lines starts with 'vt' ) with the lines from '000.obj'.

**Comment by MilesTheProwler** [comment]
@qzane thank you for reply. Can I have your social account to contact ? I have many questions to ask about your model. 
I use my own obj SMPL file from other repo and got this error. 

```
Traceback (most recent call last):
  File "demo.py", line 120, in <module>
    main(*sys.argv[1:5])
  File "demo.py", line 88, in main
    textured_smplx.get_texture_SMPL(f_img, f_obj, f_pkl, npath, 'front', template_obj)
  File "C:\Users\ADMIN\Desktop\textured_smplx\textured_smplx.py", line 56, in get_texture_SMPL
    rmat = np.array(data['camera_rotation']).reshape(3,3)
KeyError: 'camera_rotation'


```
Thank you.
